### ISSUE TITLE
How do I use this gem for tracking events in a single page app (SPA)?

### ISSUE THREAD

**Issue by avk** [swiftype/meta_events#22]
I have a single page app (SPA) and I'm interested in using [Frontend Events](https://github.com/swiftype/meta_events#frontend-events). According to the docs, I have to register any events I might fire from a page using `meta_events_define_frontend_event`. 

This seems highly impractical for a SPA, as I'd have to dump every event I declare in `config/meta_events.rb` into a gargantuan `before_filter` in some top-level controller. Wouldn't it be more practical to serialize `config/meta_events.rb` as JSON and somehow preload it as part of `<%= meta_events_frontend_events_javascript %>`? 

[Auto-Tracking](https://github.com/swiftype/meta_events#auto-tracking) also seems irrelevant for SPAs because I have access to none of the `ActionView` helpers in a JavaScript-driven SPA. 

Am I missing something? How are folks integrating the **meta_events** gem with SPAs?

**Comment by avk** [comment]
Given this has been open for almost 3 weeks with no response, I'm going to assume this repo isn't actively being maintained.

**Comment by ageweke** [comment]
@avk — I apologize for the delay; we've been busy here, and I think nobody saw an obvious answer to your question. I’m the original author, though, and want to answer your question.

`meta_events` may not be the right answer for a SPA. Here’s how I’d think about it:
- If most of your events are triggered by actions that involve hitting the server (via an AJAX call), you could use `meta_events` as normal, and just fire it from the backend. In my experience, that's more reliable, and you often have access to more data (because you can send server-side data to Mixpanel that you might not want to expose directly to the JS).
- If most of your events are triggered by actions that are purely front-end and don't involve the server at all, `meta_events` probably simply isn't a good solution, for exactly the reasons you mention above. If I were building a SPA where most analytics events were triggered by purely front-end actions, I'd either call directly to Mixpanel via JS, or, depending on scale, build something like `meta_events` purely in JavaScript directly.

Does that help?

**Comment by avk** [comment]
Thanks for the clarification.
